on:
  push:
    branches:
      - "feature/ci-refactoring"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open
        - run: echo "Your PR is ${PR}"
          if: success() && steps.findPr.outputs.number
            env:
              PR: ${{ steps.findPr.outputs.pr }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
            issue-number: ${{PR}}
            body: |
              ${PR}