on:
  push:
    branches:
      - "feature/ci-refactoring"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
            issue-number: ${{ github.event.pull_request.number }}
            body: |
              This comment was written by a bot!
            reactions: rocket