on: [push]

jobs:
  build:
    name: Comment a pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find . -type f -name "*.rs" -printf '%s\t' -exec basename \{} .contract \; | sort -k2