on:
  push:
    branches:
      - "feature/ci-refactoring"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: open

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
            issue-number: ${{ steps.findPr.outputs.pr }}
            body: |
              ${PR}