on:
  push:
    branches:
      - "feature/ci-refactoring"

jobs:
  build:
    name: Comment a pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            My comment

      - name: Check outputs
        run: |
          find . -type f -name "*.rs"